FROM alpine:edge

RUN echo "@v3.4 http://dl-cdn.alpinelinux.org/alpine/v3.4/main" >> /etc/apk/repositories
RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk update

RUN apk add \
        python2 \
        py2-pip \
        git \
        gcc \
        g++ \
        python-dev \
        swig@v3.4 \
        py-qt@testing \
        icu-libs \
        mesa-dri-swrast \
        sdl \
        sdl-dev \
        sdl_image-dev \
        sdl_mixer-dev

RUN git clone --depth 1 http://github.com/hugoruscitti/pilas /code

RUN pip install --upgrade pip
RUN pip install box2d

RUN adduser -D pilas

WORKDIR /code

CMD ./bin/pilasengine
